/* MarquesMater V8.33 — conta, encomendas, dados do cliente e acompanhamento */
(function(){
 const KEY='mm_demo_account_v87',ORDERS='mm_orders_v87';
 function get(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch(e){return null}}
 function set(v){localStorage.setItem(KEY,JSON.stringify(v))}
 function money(n){return Number(n||0).toFixed(2).replace('.',',')+' €'}
 function optionText(o){return Object.entries(o||{}).map(([k,v])=>`${k}: ${v}`).join(' · ')}
 function statusInfo(o){const s=String(o.status||'Recebida · DEMO').toLowerCase();if(s.includes('conclu'))return[4,'Concluída','A sua encomenda foi concluída. Obrigado pela sua confiança.'];if(s.includes('enviad')||s.includes('levantamento')||s.includes('pronta'))return[3,'Enviada / pronta para levantamento','A sua encomenda já avançou para a fase de envio ou está pronta para levantamento.'];if(s.includes('prepara'))return[2,'Em preparação','Estamos a preparar a sua encomenda para envio.'];return[1,'Encomenda recebida','Recebemos a sua encomenda e estamos a processá-la. Iremos atualizá-la assim que avançar para a próxima etapa.']}
 function statusTrack(o){const info=statusInfo(o),labels=['Encomenda recebida','Em preparação','Enviada','Concluída'];return `<div class="v832-status"><div class="v832-track">${labels.map((label,i)=>`<div class="v832-step ${i+1<info[0]?'done':i+1===info[0]?'current':''}"><b>${i+1<info[0]?'✓':i+1}</b><span>${label}${i===2?'<small>ou pronta para levantamento</small>':''}</span><em>${i+1===1&&info[0]>=1?(o.date||''):'—'}</em></div>`).join('')}</div><div class="v832-current"><strong>Estado atual: ${info[1]}</strong><span>${info[2]}</span></div></div>`}
 function sidebar(){return `<aside class="v832-sidebar"><a href="account.html" class="active">⌂ <span>A minha conta</span></a><a href="account-data.html">♙ <span>Os meus dados</span></a><a href="account.html#orders" class="active2">▣ <span>As minhas encomendas</span></a><a href="favorites.html">♡ <span>Os meus favoritos</span></a><a href="addresses.html">⌖ <span>Os meus endereços</span></a><button id="logoutSide">↪ <span>Terminar sessão</span></button></aside>`}
 function customerBlock(o){const c=o.customer||{};const delivery=c.delivery||'';return `<div class="v833-customer"><h3>Dados do cliente</h3><div class="v833-customer-grid"><div><span>Nome</span><strong>${c.name||'—'}</strong></div><div><span>Email</span><strong>${c.email||'—'}</strong></div><div><span>Telefone</span><strong>${c.phone||'—'}</strong></div><div><span>NIF</span><strong>${c.nif||'—'}</strong></div><div class="wide"><span>Morada de entrega</span><strong>${delivery==='Entrega em Portugal Continental'?[c.address,c.zip,c.city].filter(Boolean).join(' · ')||'—':'Levantamento em loja'}</strong></div></div></div>`}
 function render(){const box=document.getElementById('accountApp');if(!box)return;const u=get();if(u){box.innerHTML=`<div class="v832-breadcrumb"><span>A minha conta</span><b>›</b><span>As minhas encomendas</span></div><div class="v832-layout">${sidebar()}<section class="v832-main"><div class="v832-title"><div><h1>As minhas encomendas</h1><p>Acompanha aqui todas as tuas encomendas e o respetivo estado.</p></div></div><div id="orderHistory"></div></section></div>`;document.getElementById('logoutSide').onclick=()=>{localStorage.removeItem(KEY);render()};renderOrders()}else{box.innerHTML=`<div class="v85-account-card"><h2>Entrar</h2><label>Email</label><input id="demoEmail" type="email" value="demo@marquesmater.pt"><label>Palavra-passe</label><input id="demoPass" type="password" value="1234"><div class="v85-account-actions"><button class="btn orange" id="demoLogin">ENTRAR</button><button class="btn dark" id="demoCreate">CRIAR CONTA DEMO</button></div><div class="v87-demo">Conta de demonstração: <b>demo@marquesmater.pt</b> · palavra-passe <b>1234</b>. Serve apenas para testar a loja.</div></div>`;document.getElementById('demoLogin').onclick=login;document.getElementById('demoCreate').onclick=login}}
 function login(){const email=document.getElementById('demoEmail').value.trim(),pass=document.getElementById('demoPass').value;if((email==='demo@marquesmater.pt'&&pass==='1234')||email){set({email:email||'demo@marquesmater.pt',demo:true});render()}else alert('Indica um email.')}
 function renderOrders(){const box=document.getElementById('orderHistory');if(!box)return;let orders=[];try{orders=JSON.parse(localStorage.getItem(ORDERS))||[]}catch(e){}if(!orders.length){box.innerHTML='<div class="v832-empty"><strong>Ainda não tens encomendas.</strong><span>Quando fizeres uma compra, o acompanhamento aparecerá aqui.</span><a href="categories.html">VER CATEGORIAS</a></div>';return}box.innerHTML=orders.slice().reverse().map((o,i)=>{const id='ord'+i,info=statusInfo(o);return `<article class="v832-order"><header class="v832-order-head"><div><div class="v832-order-crumb">Encomenda</div><h2>#${o.number||'DEMO'}</h2><p>${o.date||''} · ${(o.items||[]).length} artigo${(o.items||[]).length===1?'':'s'} · ${money(o.total)}</p></div><div class="v832-order-actions"><span class="v832-status-pill">${info[1]}</span><button data-order="${id}">VER DETALHES</button></div></header><div class="v832-details" id="${id}">${statusTrack(o)}${customerBlock(o)}<h3>Artigos da encomenda</h3>${(o.items||[]).map(x=>`<div class="v832-product"><img src="${x.image||''}" alt=""><div class="meta"><span>${x.brand||''}</span><b>${x.name}</b>${optionText(x.options)?`<small>${optionText(x.options)}</small>`:''}</div><div class="price"><strong>${money(x.price*x.qty)}</strong><span>Qtd: ${x.qty}</span></div></div>`).join('')}<div class="v832-info-row"><span>🚚 Entrega</span><strong>${o.customer?.delivery||'—'}</strong></div><div class="v832-info-row"><span>▣ Pagamento</span><strong>${o.customer?.payment||'—'}</strong></div><div class="v832-total"><strong>Total</strong><strong>${money(o.total)}</strong></div><div class="v832-actions"><a href="categories.html">CONTINUAR A COMPRAR</a></div><div class="v832-help"><strong>ⓘ Informações úteis</strong><span>✓ Poderás acompanhar o estado da tua encomenda nesta página.</span><span>✓ O estado será atualizado quando a encomenda avançar.</span><span>✓ Em caso de dúvidas, contacta o apoio ao cliente.</span></div></div></article>`}).join('');box.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.order).classList.toggle('open'))}
 window.MMAccount={get,login,render};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
