/* MarquesMater V8.7 — conta demo */
(function(){
 const KEY='mm_demo_account_v87';
 function get(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch(e){return null}}
 function set(v){localStorage.setItem(KEY,JSON.stringify(v))}
 function render(){const box=document.getElementById('accountApp');if(!box)return;const u=get();if(u){box.innerHTML=`<div class="v87-login-ok"><div>👤 Sessão iniciada como <span class="v87-user">${u.email}</span></div><button class="v87-logout" id="logoutDemo">Terminar sessão</button></div><div class="v87-account-grid"><section class="v87-panel"><h2>As minhas encomendas</h2><div id="orderHistory"></div></section><section class="v87-panel"><h2>A minha conta</h2><p>Conta DEMO ativa para testar a experiência de compra.</p><div class="v87-demo">Esta conta é apenas para simulação. Não existe pagamento nem encomenda real.</div><div class="v85-links"><a href="favorites.html">♥ Favoritos</a><a href="cart.html">🛒 Carrinho</a><a href="category.html?cat=Construção">Continuar a comprar</a></div></section></div>`;document.getElementById('logoutDemo').onclick=()=>{localStorage.removeItem(KEY);render()};renderOrders()}else{box.innerHTML=`<div class="v85-account-card"><h2>Entrar</h2><label>Email</label><input id="demoEmail" type="email" value="demo@marquesmater.pt"><label>Palavra-passe</label><input id="demoPass" type="password" value="1234"><div class="v85-account-actions"><button class="btn orange" id="demoLogin">ENTRAR</button><button class="btn dark" id="demoCreate">CRIAR CONTA DEMO</button></div><div class="v87-demo">Conta de demonstração: <b>demo@marquesmater.pt</b> · palavra-passe <b>1234</b>. Serve apenas para testar a loja.</div></div>`;document.getElementById('demoLogin').onclick=login;document.getElementById('demoCreate').onclick=login}}
 function login(){const email=document.getElementById('demoEmail').value.trim(),pass=document.getElementById('demoPass').value;if((email==='demo@marquesmater.pt'&&pass==='1234')||email){set({email:email||'demo@marquesmater.pt',demo:true});render()}else alert('Indica um email.')}
 function renderOrders(){const box=document.getElementById('orderHistory');if(!box)return;let orders=[];try{orders=JSON.parse(localStorage.getItem('mm_orders_v87'))||[]}catch(e){};box.innerHTML=orders.length?orders.slice().reverse().map(o=>`<div class="v87-order"><strong>${o.number}</strong><span>${o.date} · ${o.total.toFixed(2).replace('.',',')} € · ${o.status}</span></div>`).join(''):'<p>Ainda não tens encomendas.</p>'}
 window.MMAccount={get,login,render};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();