window.MARQUES_CATALOG = [
  {sku:"NEUCE-FACHADAS-15L", brand:"NEUCE", name:"Tinta Fachadas — Exterior", category:"Tintas", subcategory:"Tintas de Fachadas", type:"paint", price:49.90, oldPrice:59.90, stock:"Em stock", image:"images/paint.svg", badge:"Promoção", description:"Tinta para fachadas e superfícies exteriores, com boa cobertura e acabamento durável.", options:{"Embalagem":["2,5 L","5 L","15 L"],"Cor":["Branco","Marfim","Cinza","Cor à escolha"],"Acabamento":["Mate","Acetinado"]}, specs:["Aplicação: exterior","Rendimento: consultar ficha técnica","Secagem: conforme condições ambientais","Diluição: conforme ficha técnica"]},
  {sku:"NEUCEMATT-15L", brand:"NEUCE", name:"NeuceMatt — Tinta Interior Mate", category:"Tintas", subcategory:"Tintas de Interior", type:"paint", price:39.90, stock:"Em stock", image:"images/paint.svg", description:"Tinta mate para paredes interiores, pensada para um acabamento uniforme.", options:{"Embalagem":["2,5 L","5 L","15 L"],"Cor":["Branco","Base para afinação"],"Acabamento":["Mate"]}, specs:["Aplicação: interior","Acabamento: mate","Base: branca / afinação","Rendimento: consultar ficha técnica"]},
  {sku:"SIL001", brand:"Soudal", name:"Silicone Sanitário Neutro", category:"Selantes & Colas", subcategory:"Silicones", type:"sealant", price:7.95, stock:"Em stock", image:"images/silicone.svg", description:"Selante de silicone para juntas em cozinhas, casas de banho e zonas húmidas.", options:{"Tipo":["Sanitário","Neutro"],"Cor":["Branco","Transparente","Cinza","Preto"],"Volume":["280 ml","300 ml"]}, specs:["Aplicação: juntas sanitárias","Cura: conforme ficha técnica","Resistência: humidade","Formato: cartucho"]},
  {sku:"SOU-PU-001", brand:"Soudal", name:"Espuma PU Pistola", category:"Selantes & Colas", subcategory:"Espumas PU", type:"sealant", price:9.90, stock:"Em stock", image:"images/pu.svg", description:"Espuma de poliuretano para enchimento, isolamento e montagem.", options:{"Aplicação":["Pistola","Manual"],"Capacidade":["750 ml"],"Expansão":["Standard","Baixa expansão"]}, specs:["Base: poliuretano","Aplicação: montagem e isolamento","Formato: lata","Uso: construção"]},
  {sku:"LAMP-E27-10W", brand:"MarquesMater", name:"Lâmpada LED A60 E27 10W", category:"Iluminação", subcategory:"Lâmpadas LED", type:"lamp", price:2.49, stock:"Em stock", image:"images/lamp.svg", badge:"Mais vendido", description:"Lâmpada LED para iluminação geral, disponível em diferentes temperaturas de cor.", options:{"Casquilho":["E27"],"Potência":["10 W","12 W","15 W"],"Temperatura de cor":["3000 K","4000 K","6500 K"]}, specs:["Fluxo luminoso: conforme versão","Tensão: 220–240 V","Formato: A60","Tecnologia: LED"]},
  {sku:"FERR-M8-50", brand:"MarquesMater", name:"Parafuso Sextavado M8 x 50 mm", category:"Ferragens", subcategory:"Parafusos e Fixação", type:"hardware", price:4.90, stock:"Em stock", image:"images/hardware.svg", description:"Parafuso sextavado para aplicações de fixação em construção e manutenção.", options:{"Medida":["M6 x 40 mm","M8 x 50 mm","M10 x 60 mm"],"Material":["Aço zincado","Inox"],"Quantidade":["10 un.","25 un.","50 un."]}, specs:["Cabeça: sextavada","Rosca: métrica","Acabamento: zincado / inox","Uso: fixação"]},
  {sku:"CAN-PPR-25", brand:"MarquesMater", name:"Tubo PPR 25 mm", category:"Canalização", subcategory:"Tubos e Acessórios", type:"plumbing", price:8.90, stock:"Em stock", image:"images/plumbing.svg", description:"Tubo PPR para instalações de água, com várias opções de comprimento e pressão.", options:{"Diâmetro":["20 mm","25 mm","32 mm"],"Comprimento":["2 m","4 m"],"Pressão":["PN16","PN20"]}, specs:["Material: PPR","Aplicação: água","Comprimentos: várias opções","Pressão: conforme versão"]},
  {sku:"EPI-CAP-001", brand:"MarquesMater", name:"Capacete de Proteção", category:"EPI", subcategory:"Proteção da Cabeça", type:"epi", price:12.90, stock:"Em stock", image:"images/epi.svg", description:"Capacete de proteção para trabalhos de construção e manutenção.", options:{"Tamanho":["Único ajustável"],"Cor":["Branco","Amarelo","Azul"]}, specs:["Proteção: cabeça","Ajuste: regulável","Uso: construção","Conformidade: conforme modelo"]},
  {sku:"RHD01075-B22", brand:"RIDA", name:"Berbequim/Perfurador RIDA 20V", category:"RIDA", subcategory:"Berbequins e Aparafusadoras", type:"rida", price:149.90, stock:"Em stock", image:"images/drill.svg", description:"Berbequim/perfurador sem fios para construção e bricolage.", options:{"Bateria":["2 Ah","4 Ah","6 Ah"],"Kit":["Máquina","Máquina + 2 baterias + carregador","Kit + mala BMC"]}, specs:["Tensão: 20 V","Motor: sem escovas","Uso: construção e bricolage","Acessórios: conforme kit"]},
  {sku:"JARD-SERRA-001", brand:"RIDA", name:"Serra de Poda a Bateria", category:"Jardim & Agricultura", subcategory:"Serras de Poda", type:"garden", price:119.90, stock:"Em stock", image:"images/garden.svg", description:"Serra compacta para poda e manutenção de árvores e arbustos.", options:{"Bateria":["2 Ah","4 Ah","6 Ah"],"Lâmina":["6\"","8\""]}, specs:["Alimentação: bateria","Aplicação: poda","Compatibilidade: conforme sistema","Kit: conforme versão"]},
  {sku:"CAB-3G15-25", brand:"MarquesMater", name:"Cabo Elétrico 3G1,5 mm²", category:"Eletricidade", subcategory:"Cabos e Fios", type:"electric", price:24.90, stock:"Em stock", image:"images/electric.svg", description:"Cabo elétrico para instalações e extensões, vendido em rolo.", options:{"Secção":["3G1,5 mm²","3G2,5 mm²"],"Comprimento":["25 m","50 m","100 m"]}, specs:["Condutor: cobre","Tensão: conforme aplicação","Formato: rolo","Aplicação: instalações elétricas"]},
  {sku:"CIM-25-001", brand:"MarquesMater", name:"Cimento Portland 25 kg", category:"Construção", subcategory:"Cimentos e Argamassas", type:"cement", price:6.50, stock:"Em stock", image:"images/cement.svg", description:"Cimento para trabalhos de construção e reparação.", options:{"Tipo":["Portland","Estrutural"],"Embalagem":["25 kg","35 kg"]}, specs:["Aplicação: construção","Embalagem: saco","Resistência: conforme classe","Armazenamento: local seco"]},
  {sku:"CASA-ORG-001", brand:"MarquesMater", name:"Caixa Organizadora Multiusos", category:"Casa", subcategory:"Organização", type:"home", price:8.90, stock:"Em stock", image:"images/home.svg", description:"Caixa organizadora para ferramentas, acessórios e arrumação doméstica.", options:{"Tamanho":["5 L","12 L","25 L"],"Cor":["Transparente","Preto"]}, specs:["Material: plástico","Uso: organização","Tampa: conforme modelo","Formato: empilhável"]},
  {sku:"PROMO-DISC-125", brand:"MarquesMater", name:"Disco Diamante para Betão 125 mm", category:"Promoções", subcategory:"Oportunidades", type:"disc", price:14.90, oldPrice:19.90, stock:"Em stock", image:"images/disc.svg", badge:"Promoção", description:"Disco diamantado para corte de materiais de construção.", options:{"Diâmetro":["115 mm","125 mm","230 mm"],"Aplicação":["Betão","Betão armado","Alvenaria"]}, specs:["Diâmetro: conforme versão","Aplicação: corte","Segmento: diamantado","Uso: profissional"]}
];
window.MM_CATEGORIES=["Construção","Ferramentas","Tintas","Selantes & Colas","Jardim & Agricultura","Ferragens","Eletricidade","Iluminação","Canalização","Casa","EPI","RIDA","Promoções"];
window.MM_NAV=MM_CATEGORIES.map(c=>`<a href="category.html?cat=${encodeURIComponent(c)}">${c}</a>`).join('');
window.MM_SUBCATEGORIES={"Construção":["Cimentos e Argamassas","Impermeabilização","Isolamentos","Materiais de Obra"],"Ferramentas":["Ferramentas Manuais","Ferramentas Elétricas","Corte e Desbaste"],"Tintas":["Tintas de Interior","Tintas de Fachadas","Primários","Vernizes"],"Selantes & Colas":["Silicones","Espumas PU","Colas","Selantes"],"Jardim & Agricultura":["Serras de Poda","Irrigação","Acessórios"],"Ferragens":["Parafusos e Fixação","Buchas","Ferragens Diversas"],"Eletricidade":["Cabos e Fios","Tomadas e Interruptores","Material Elétrico"],"Iluminação":["Lâmpadas LED","Projetores","Iluminação Exterior"],"Canalização":["Tubos e Acessórios","Torneiras","Drenagem"],"Casa":["Organização","Limpeza","Utilidades"],"EPI":["Proteção da Cabeça","Proteção das Mãos","Vestuário"],"RIDA":["Berbequins e Aparafusadoras","Rebarbadoras","Serras","Baterias e Carregadores"],"Promoções":["Ofertas","Queima de Stock","Packs","Oportunidades"]};
window.MM_VARIANT_IMAGES={"SIL001":{"Branco":"images/silicone-branco.svg","Transparente":"images/silicone-transparente.svg","Cinza":"images/silicone-cinza.svg","Preto":"images/silicone-preto.svg"},"LAMP-E27-10W":{"3000 K":"images/lamp-3000k.svg","4000 K":"images/lamp-4000k.svg","6500 K":"images/lamp-6500k.svg"},"NEUCE-FACHADAS-15L":{"Branco":"images/paint-branco.svg","Marfim":"images/paint-marfim.svg","Cinza":"images/paint-cinza.svg"},"NEUCEMATT-15L":{"Branco":"images/paint-branco.svg"}};