/* MarquesMater V8.21 — hero mobile com scroll nativo */
(function(){
  const css=document.createElement('link');css.rel='stylesheet';css.href='v8.6.css';document.head.appendChild(css);
  const style=document.createElement('style');style.textContent=`@media(max-width:700px){.heroV7 .mmCarousel{overflow-x:auto!important;overflow-y:hidden!important;-webkit-overflow-scrolling:touch!important;scroll-snap-type:x mandatory!important;touch-action:pan-x!important}.heroV7 .mmSlides{display:flex!important;width:max-content!important;min-height:430px!important;height:430px!important}.heroV7 .mmSlide{position:relative!important;inset:auto!important;flex:0 0 100vw!important;width:100vw!important;height:430px!important;min-height:430px!important;opacity:1!important;pointer-events:auto!important;scroll-snap-align:start!important;scroll-snap-stop:always!important}.heroV7 .mmSlide:not(.active){transform:none!important}.heroV7 .mmSlideCopy .pill{display:none!important}.heroV7 .mmSlideCopy h1{font-size:27px!important;line-height:1.05!important;margin:7px 0 9px!important}.heroV7 .mmSlideCopy p{font-size:13px!important;line-height:1.3!important;max-width:320px!important;margin-bottom:11px!important}.heroV7 .mmCarousel::-webkit-scrollbar{display:none!important}.heroV7 .mmCarousel{scrollbar-width:none!important}}@media(max-width:380px){.heroV7 .mmSlides{height:410px!important;min-height:410px!important}.heroV7 .mmSlide{height:410px!important;min-height:410px!important}.heroV7 .mmSlideCopy h1{font-size:25px!important}.heroV7 .mmSlideCopy p{font-size:12px!important;max-width:300px!important}}`;document.head.appendChild(style);
  const wrap=document.createElement('div');
  wrap.innerHTML=`<button class="mmChatBtn" id="mmChatBtn" aria-label="Abrir assistente">💬 Precisa de ajuda?</button><section class="mmChatPanel" id="mmChatPanel" aria-label="Assistente MarquesMater"><header class="mmChatHead"><div><strong>🤖 Assistente MarquesMater</strong><small>Ajuda a encontrar o produto certo</small></div><button class="mmChatClose" id="mmChatClose" aria-label="Fechar">×</button></header><div class="mmChatBody" id="mmChatBody"><div class="mmChatMsg">Olá! 👋 Posso ajudar-te a encontrar materiais, ferramentas, tintas, selantes e outros produtos.</div><div class="mmChatQuick"><button data-q="Preciso de ajuda a escolher um produto">Escolher produto</button><button data-q="Quero saber sobre entregas">Entregas</button><button data-q="Preciso de ajuda com tintas">Tintas</button><button data-q="Preciso de ajuda com ferramentas RIDA">Ferramentas RIDA</button></div></div><form class="mmChatForm" id="mmChatForm"><input id="mmChatInput" autocomplete="off" placeholder="Escreve a tua dúvida..."><button>Enviar</button></form></section>`;
  document.body.appendChild(wrap);
  const panel=document.getElementById('mmChatPanel'),body=document.getElementById('mmChatBody'),input=document.getElementById('mmChatInput');
  document.getElementById('mmChatBtn').onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))input.focus()};
  document.getElementById('mmChatClose').onclick=()=>panel.classList.remove('open');
  function reply(text){const t=text.toLowerCase();if(t.includes('tinta'))return 'Claro. Posso ajudar a escolher por aplicação, embalagem, cor e acabamento. Na página do produto apresentamos as variantes.';if(t.includes('rida')||t.includes('ferrament'))return 'Posso ajudar a escolher uma ferramenta RIDA por voltagem, bateria, potência e kit.';if(t.includes('entrega'))return 'A loja está preparada para informação de entrega em Portugal Continental e levantamento em loja.';if(t.includes('silicone')||t.includes('cola')||t.includes('selante'))return 'Posso ajudar a escolher o tipo, cor e volume. As variantes ficam disponíveis na página do produto.';return 'Percebi. Posso ajudar-te a encontrar o produto certo.'}
  function send(text){if(!text.trim())return;body.insertAdjacentHTML('beforeend',`<div class="mmChatMsg user">${text.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</div>`);setTimeout(()=>{body.insertAdjacentHTML('beforeend',`<div class="mmChatMsg">${reply(text)}</div>`);body.scrollTop=body.scrollHeight},250);body.scrollTop=body.scrollHeight}
  document.getElementById('mmChatForm').onsubmit=e=>{e.preventDefault();send(input.value);input.value=''};
  body.querySelectorAll('.mmChatQuick button').forEach(b=>b.onclick=()=>send(b.dataset.q));
  const bottom=document.createElement('nav');bottom.className='v8-mobile-bottom';bottom.innerHTML='<a href="index.html"><b>⌂</b><span>Início</span></a><a href="category.html?cat=Construção"><b>▦</b><span>Categorias</span></a><a href="#" onclick="document.getElementById(\'mmChatBtn\').click();return false"><b>💬</b><span>Ajuda</span></a><a href="cart.html"><b>🛒</b><span>Carrinho</span></a>';document.body.appendChild(bottom);
  const carousel=document.getElementById('carousel');
  if(carousel){
    const slides=[...carousel.querySelectorAll('.mmSlide')];
    let scrollingByCode=false,scrollTimer=null;
    function mobile(){return window.matchMedia('(max-width:700px)').matches}
    function scrollToIndex(i){if(!mobile()||!slides[i])return;scrollingByCode=true;carousel.scrollTo({left:i*carousel.clientWidth,behavior:'smooth'});setTimeout(()=>scrollingByCode=false,500)}
    if(slides.length){
      const obs=new MutationObserver(()=>{const i=slides.findIndex(s=>s.classList.contains('active'));if(i>=0)scrollToIndex(i)});obs.observe(carousel,{subtree:true,attributes:true,attributeFilter:['class']});
      carousel.addEventListener('scroll',()=>{if(!mobile()||scrollingByCode)return;clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{const i=Math.round(carousel.scrollLeft/carousel.clientWidth);if(typeof window.show==='function')window.show(i);},90)},{passive:true});
      window.addEventListener('resize',()=>{if(mobile()){const i=slides.findIndex(s=>s.classList.contains('active'));if(i>=0)carousel.scrollLeft=i*carousel.clientWidth}});
      setTimeout(()=>{const i=slides.findIndex(s=>s.classList.contains('active'));if(i>=0)carousel.scrollLeft=i*carousel.clientWidth},0);
    }
  }
  const s=document.createElement('script');s.src='js/store.js';document.body.appendChild(s);
})();
