/* MarquesMater V8 — Assistente + camada de experiência */
(function(){
  const wrap=document.createElement('div');
  wrap.innerHTML=`<button class="mmChatBtn" id="mmChatBtn" aria-label="Abrir assistente">💬 Precisa de ajuda?</button><section class="mmChatPanel" id="mmChatPanel" aria-label="Assistente MarquesMater"><header class="mmChatHead"><div><strong>🤖 Assistente MarquesMater</strong><small>Ajuda a encontrar o produto certo</small></div><button class="mmChatClose" id="mmChatClose" aria-label="Fechar">×</button></header><div class="mmChatBody" id="mmChatBody"><div class="mmChatMsg">Olá! 👋 Posso ajudar-te a encontrar materiais, ferramentas, tintas, selantes e outros produtos.</div><div class="mmChatQuick"><button data-q="Preciso de ajuda a escolher um produto">Escolher produto</button><button data-q="Quero saber sobre entregas">Entregas</button><button data-q="Preciso de ajuda com tintas">Tintas</button><button data-q="Preciso de ajuda com ferramentas RIDA">Ferramentas RIDA</button></div></div><form class="mmChatForm" id="mmChatForm"><input id="mmChatInput" autocomplete="off" placeholder="Escreve a tua dúvida..."><button>Enviar</button></form></section>`;
  document.body.appendChild(wrap);
  const panel=document.getElementById('mmChatPanel'),body=document.getElementById('mmChatBody'),input=document.getElementById('mmChatInput');
  document.getElementById('mmChatBtn').onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))input.focus()};
  document.getElementById('mmChatClose').onclick=()=>panel.classList.remove('open');
  function reply(text){const t=text.toLowerCase();if(t.includes('tinta'))return 'Claro. Posso ajudar a escolher por aplicação, embalagem, cor e acabamento. Na página do produto apresentamos as variantes.';if(t.includes('rida')||t.includes('ferrament'))return 'Posso ajudar a escolher uma ferramenta RIDA por voltagem, bateria, potência e kit.';if(t.includes('entrega'))return 'A loja está preparada para informação de entrega em Portugal Continental e levantamento em loja.';if(t.includes('silicone')||t.includes('cola')||t.includes('selante'))return 'Posso ajudar a escolher o tipo, cor e volume. As variantes ficam disponíveis na página do produto.';return 'Percebi. Posso ajudar-te a encontrar o produto certo.'}
  function send(text){if(!text.trim())return;body.insertAdjacentHTML('beforeend',`<div class="mmChatMsg user">${text.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</div>`);setTimeout(()=>{body.insertAdjacentHTML('beforeend',`<div class="mmChatMsg">${reply(text)}</div>`);body.scrollTop=body.scrollHeight},250);body.scrollTop=body.scrollHeight}
  document.getElementById('mmChatForm').onsubmit=e=>{e.preventDefault();send(input.value);input.value=''};
  body.querySelectorAll('.mmChatQuick button').forEach(b=>b.onclick=()=>send(b.dataset.q));
  const bottom=document.createElement('nav');bottom.className='v8-mobile-bottom';bottom.innerHTML='<a href="index.html"><b>⌂</b>Início</a><a href="category.html?cat=Construção"><b>▦</b>Categorias</a><a href="#" onclick="document.getElementById(\'mmChatBtn\').click();return false"><b>💬</b>Ajuda</a><a href="cart.html"><b>🛒</b>Carrinho</a>';document.body.appendChild(bottom);
  if(location.pathname.endsWith('index.html')||location.pathname==='/'||location.pathname===''){
    const featured=document.getElementById('featured');
    if(featured&&!document.querySelector('.v8-extra')){const block=document.createElement('section');block.className='wrap section v8-extra';block.innerHTML=`<div class="v8-highlight"><div><span class="v8-kicker">MARQUESMATER · V8</span><h2>Encontra a solução certa para o teu projeto.</h2><p>Construção, ferramentas, tintas, selantes, jardim, EPI e muito mais.</p><a class="btn orange" href="category.html?cat=Construção">EXPLORAR CATÁLOGO</a></div></div><div class="v8-strip"><div><span>🚚</span><div><b>Entrega em Portugal</b><span>Continente</span></div></div><div><span>🏪</span><div><b>Levantamento em loja</b><span>Loja</span></div></div><div><span>🛠</span><div><b>Produtos profissionais</b><span>Para obra e manutenção</span></div></div><div><span>✓</span><div><b>Informação técnica</b><span>Fichas e características</span></div></div></div>`;featured.closest('.section')?.after(block)}
  }
  const s=document.createElement('script');s.src='js/store.js';document.body.appendChild(s);
})();
