/* MarquesMater V8.7.1 — checkout demo completo */
(function(){
 const box=document.getElementById('checkoutApp');if(!box)return;
 const ORDERS='mm_orders_v87';
 function money(n){return Number(n||0).toFixed(2).replace('.',',')+' €'}
 function cart(){return window.MMStore?MMStore.state().cart:[]}
 function calc(){let subtotal=0,items=[];cart().forEach(x=>{const p=MMStore.product(x.sku);if(!p)return;let price=p.price;if(x.options?.Embalagem&&p.variantPrices?.Embalagem?.[x.options.Embalagem])price=p.variantPrices.Embalagem[x.options.Embalagem];const qty=x.qty||1;subtotal+=price*qty;items.push({sku:x.sku,name:p.name,qty,price,options:x.options||{},image:p.image,brand:p.brand})});return{subtotal,items}}
 function render(){const c=calc();if(!c.items.length){box.innerHTML='<div class="v871-empty"><h2>O teu carrinho está vazio</h2><p>Adiciona pelo menos um produto antes de finalizar a encomenda.</p><a class="btn orange" href="category.html?cat=Construção">VOLTAR À LOJA</a></div>';return}box.innerHTML=`<div class="v871-checkout"><form id="checkoutForm" class="v871-form"><section class="v871-panel"><h2>1. Dados do cliente</h2><div class="v871-grid"><label>Nome completo<input required name="name" value="Cliente Demo"></label><label>Email<input required type="email" name="email" value="demo@marquesmater.pt"></label><label>Telefone<input required name="phone" value="912 345 678"></label><label>NIF <span>(opcional)</span><input name="nif"></label></div></section><section class="v871-panel"><h2>2. Método de entrega</h2><label class="v871-radio"><input type="radio" name="delivery" value="Levantamento em loja" checked> <b>Levantamento em loja</b><span>Grátis</span></label><label class="v871-radio"><input type="radio" name="delivery" value="Entrega em Portugal Continental"> <b>Entrega em Portugal Continental</b><span>4,90 €</span></label><div id="addressBox" class="v871-address"><div class="v871-grid"><label>Morada<input name="address" value="Rua Exemplo, 1"></label><label>Código Postal<input name="zip" value="3100-000"></label><label>Localidade<input name="city" value="Pombal"></label></div></div></section><section class="v871-panel"><h2>3. Pagamento</h2><label class="v871-radio"><input type="radio" name="payment" value="Pagamento DEMO" checked> <b>💳 Pagamento DEMO</b><span>Simulação</span></label><label class="v871-radio"><input type="radio" name="payment" value="Transferência DEMO"> <b>🏦 Transferência DEMO</b><span>Simulação</span></label><div class="v871-demo">🔒 Esta compra é apenas uma simulação. Não é efetuado qualquer pagamento real.</div></section><button class="btn orange v871-confirm" type="submit">CONFIRMAR ENCOMENDA DEMO</button></form><aside class="v871-summary"><h2>Resumo da encomenda</h2>${c.items.map(i=>`<div class="v871-item"><span>${i.name}${i.options?.Embalagem?' · '+i.options.Embalagem:''} × ${i.qty}</span><strong>${money(i.price*i.qty)}</strong></div>`).join('')}<hr><div><span>Subtotal</span><strong>${money(c.subtotal)}</strong></div><div><span>Entrega</span><strong id="deliveryPrice">Grátis</strong></div><div class="v871-total"><span>Total</span><strong id="totalPrice">${money(c.subtotal)}</strong></div></aside></div>`;
 const form=document.getElementById('checkoutForm'),addr=document.getElementById('addressBox'),dp=document.getElementById('deliveryPrice'),tp=document.getElementById('totalPrice');
 function update(){const delivery=form.querySelector('input[name="delivery"]:checked').value==='Entrega em Portugal Continental';const fee=delivery?4.9:0;addr.style.display=delivery?'block':'none';dp.textContent=fee?money(fee):'Grátis';tp.textContent=money(c.subtotal+fee)}
 form.querySelectorAll('input[name="delivery"]').forEach(x=>x.onchange=update);update();
 form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());const total=c.subtotal+(data.delivery==='Entrega em Portugal Continental'?4.9:0);const number='MM-DEMO-'+String(Date.now()).slice(-7);let all=[];try{all=JSON.parse(localStorage.getItem(ORDERS))||[]}catch(_){}all.push({number,date:new Date().toLocaleString('pt-PT'),total,status:'Recebida · DEMO',items:c.items,customer:data});localStorage.setItem(ORDERS,JSON.stringify(all));if(window.MMStore)MMStore.clearCart();box.innerHTML=`<div class="v871-success"><div class="v871-check">✓</div><span class="eyebrow dark">ENCOMENDA DEMO</span><h2>Encomenda confirmada!</h2><p>Obrigado, ${data.name||'cliente'}. A tua encomenda foi registada apenas para simulação.</p><div class="v871-order-number"><small>Número da encomenda</small><strong>${number}</strong></div><div class="v871-success-info"><b>Total: ${money(total)}</b><span>${data.delivery}</span><span>${data.payment}</span></div><a class="btn orange" href="account.html">VER AS MINHAS ENCOMENDAS</a><a class="btn dark" href="index.html">CONTINUAR A COMPRAR</a></div>`}
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
