/* MarquesMater V8.9 — conta, favoritos e carrinho local */
(function(){
 if(window.MMStore)return;
 const css=document.createElement('link');css.rel='stylesheet';css.href='v8.8.css';document.head.appendChild(css);
 const css89=document.createElement('link');css89.rel='stylesheet';css89.href='v8.9.css';document.head.appendChild(css89);
 const css813=document.createElement('link');css813.rel='stylesheet';css813.href='v8.13-cart.css';document.head.appendChild(css813);
 const css813fav=document.createElement('link');css813fav.rel='stylesheet';css813fav.href='v8.13-favorites.css';document.head.appendChild(css813fav);
 const KEY='mm_store_v85';
 function state(){try{return JSON.parse(localStorage.getItem(KEY))||{favorites:[],cart:[]}}catch(e){return {favorites:[],cart:[]}}}
 function save(s){localStorage.setItem(KEY,JSON.stringify(s));sync()}
 function skuFromUrl(){return new URLSearchParams(location.search).get('sku')}
 function product(sku){return (window.MARQUES_CATALOG||[]).find(p=>p.sku===sku)}
 function sync(){const s=state(),count=s.cart.reduce((a,x)=>a+(x.qty||1),0),favCount=s.favorites.length;document.querySelectorAll('#cartCount').forEach(x=>x.textContent=count);document.querySelectorAll('[data-fav-count]').forEach(x=>x.textContent=favCount);document.querySelectorAll('.actions a,.head-actions a').forEach(a=>{const txt=(a.innerText||'').toLowerCase();if(txt.includes('favoritos')||a.href.includes('favorites.html')){a.classList.toggle('mm-has-favorites',favCount>0);const icon=a.querySelector('.mm-fav-icon');if(icon)icon.textContent=favCount>0?'♥':'♡'}});document.querySelectorAll('a[href*="cart.html"]').forEach(a=>{if(a.closest('.actions,.head-actions'))return;let b=a.querySelector('.mm-cart-badge');if(!b){b=document.createElement('b');b.className='mm-cart-badge';b.setAttribute('aria-label','Itens no carrinho');a.appendChild(b)}b.textContent=count;b.style.display=count?'block':'none'})}
 function addFavorite(sku){const s=state();if(!s.favorites.includes(sku))s.favorites.push(sku);else s.favorites=s.favorites.filter(x=>x!==sku);save(s);return s.favorites.includes(sku)}
 function addCart(sku,qty,options){if(!sku)return;const s=state(),key=sku+'|'+JSON.stringify(options||{}),found=s.cart.find(x=>x.key===key);if(found)found.qty+=(qty||1);else s.cart.push({key,sku,qty:qty||1,options:options||{}});save(s)}
 function removeCart(key){const s=state();s.cart=s.cart.filter(x=>x.key!==key);save(s)}
 function updateCartQty(key,delta){const s=state(),x=s.cart.find(i=>i.key===key);if(!x)return;if(delta>0)x.qty=(x.qty||1)+delta;else x.qty=Math.max(1,(x.qty||1)+delta);save(s)}
 function clearCart(){localStorage.removeItem(KEY);sync()}
 window.MMStore={state,save,addFavorite,addCart,removeCart,updateCartQty,clearCart,sync,product};
 function links(){document.querySelectorAll('.actions a,.head-actions a').forEach((a,i)=>{if(i===0)a.href='account.html';if(i===1)a.href='favorites.html';if(i===2)a.href='cart.html'})}
 function enhanceHeader(){document.querySelectorAll('.actions a,.head-actions a').forEach(a=>{const txt=(a.innerText||'').toLowerCase();if(!(txt.includes('favoritos')||a.href.includes('favorites.html')))return;if(!a.querySelector('.mm-fav-icon')){const small=a.querySelector('small');const icon=document.createElement('span');icon.className='mm-fav-icon';icon.setAttribute('aria-hidden','true');const raw=(a.childNodes[0]?.textContent||'').trim();if(raw)a.childNodes[0].textContent='';a.insertBefore(icon,a.firstChild);if(!small)a.insertAdjacentHTML('beforeend','<small>Favoritos <b data-fav-count>0</b></small>')}});sync()}
 function enhanceCards(){const s=state();document.querySelectorAll('.product').forEach(card=>{const a=card.querySelector('a[href*="product.html?sku="]');if(!a)return;const sku=new URL(a.href,location.href).searchParams.get('sku');if(card.querySelector('.v85-fav,.v84-fav'))return;const b=document.createElement('button');b.className='v85-fav'+(s.favorites.includes(sku)?' active':'');b.type='button';b.title=s.favorites.includes(sku)?'Remover dos favoritos':'Adicionar aos favoritos';b.innerHTML=s.favorites.includes(sku)?'♥':'♡';b.onclick=e=>{e.preventDefault();e.stopPropagation();const on=addFavorite(sku);b.classList.toggle('active',on);b.title=on?'Remover dos favoritos':'Adicionar aos favoritos';b.innerHTML=on?'♥':'♡'};card.style.position='relative';card.appendChild(b)})}
 function enhanceProduct(){const sku=skuFromUrl(),p=product(sku);if(!p)return;const root=document.getElementById('root');if(!root||root.querySelector('.v85-product-fav'))return;const active=state().favorites.includes(sku);const b=document.createElement('button');b.className='v85-product-fav'+(active?' active':'');b.type='button';b.innerHTML=(active?'♥':'♡')+' <span>'+ (active?'Guardado nos favoritos':'Guardar nos favoritos') +'</span>';b.onclick=()=>{const on=addFavorite(sku);b.classList.toggle('active',on);b.innerHTML=(on?'♥':'♡')+' <span>'+ (on?'Guardado nos favoritos':'Guardar nos favoritos')+'</span>'};const details=root.querySelector('.v6-details');if(details)details.insertBefore(b,details.firstChild);const add=root.querySelector('.v6-cart');if(add&&!add.dataset.v85){add.addEventListener('click',()=>{const opts={};root.querySelectorAll('.v6-option').forEach(o=>{const k=o.querySelector('label')?.textContent;const v=o.querySelector('.selected')?.dataset.value||o.querySelector('.selected')?.textContent;if(k&&v)opts[k]=v.trim()});addCart(sku,Number(document.getElementById('qty')?.textContent||1),opts)});add.dataset.v85='1'}}
 function renderFavorites(){const box=document.getElementById('favoritesApp');if(!box)return;const s=state(),items=s.favorites.map(product).filter(Boolean);box.innerHTML=items.length?`<div class="v85-grid">${items.map(p=>`<article class="v85-list-card"><a href="product.html?sku=${encodeURIComponent(p.sku)}"><img src="${p.image}" alt="${p.name}"><div><small>${p.brand}</small><h3>${p.name}</h3><strong>${p.variantPrices?.Embalagem?'Desde '+Math.min(...Object.values(p.variantPrices.Embalagem)).toFixed(2).replace('.',',')+' €':p.price.toFixed(2).replace('.',',')+' €'}</strong></div></a><button data-remove="${p.sku}">♥ Remover</button></article>`).join('')}</div>`:`<div class="v85-empty"><div>♡</div><h2>Ainda não tens favoritos</h2><p>Guarda aqui os produtos que queres comparar ou comprar mais tarde.</p><a class="btn orange" href="category.html?cat=Construção">EXPLORAR PRODUTOS</a></div>`;box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{addFavorite(b.dataset.remove);renderFavorites()})}
 function optionText(options){return Object.entries(options||{}).map(([k,v])=>`${k}: ${v}`).join(' · ')}
 function renderCart(){const box=document.getElementById('cartApp');if(!box)return;const s=state();if(!s.cart.length){box.innerHTML=`<div class="v85-empty"><div>🛒</div><h2>O teu carrinho está vazio</h2><p>Adiciona produtos e as respetivas variantes. O carrinho fica guardado neste dispositivo.</p><a class="btn orange" href="category.html?cat=Construção">COMEÇAR A COMPRAR</a></div>`;return}let total=0;const rows=s.cart.map(x=>{const p=product(x.sku);if(!p)return '';let price=p.price;if(x.options?.Embalagem&&p.variantPrices?.Embalagem?.[x.options.Embalagem])price=p.variantPrices.Embalagem[x.options.Embalagem];const qty=x.qty||1;total+=price*qty;const opts=optionText(x.options);return `<article class="v85-cart-row"><img src="${p.image}" alt="${p.name}"><div class="v85-cart-info"><small>${p.brand}</small><h3>${p.name}</h3>${opts?`<span class="v89-variant">${opts}</span>`:''}<div class="v88-cart-qtybox"><button class="v88-qtybtn" data-qty="-1" data-key="${encodeURIComponent(x.key)}">−</button><span class="v88-qtynum">${qty}</span><button class="v88-qtybtn" data-qty="1" data-key="${encodeURIComponent(x.key)}">+</button></div><button class="v88-remove" data-remove-cart="${encodeURIComponent(x.key)}">Remover</button></div><div class="v85-cart-qty">${qty} × ${price.toFixed(2).replace('.',',')} €</div><strong>${(price*qty).toFixed(2).replace('.',',')} €</strong></article>`}).join('');box.innerHTML=`<div class="v85-cart-layout"><div class="v85-cart-list">${rows}</div><aside class="v85-summary"><h2>Resumo</h2><div><span>Subtotal</span><strong>${total.toFixed(2).replace('.',',')} €</strong></div><p>IVA incluído · portes calculados no checkout</p><a class="btn orange" href="checkout.html">CONTINUAR PARA CHECKOUT</a><button class="btn dark" id="clearV85">LIMPAR CARRINHO</button></aside></div>`;box.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>{updateCartQty(decodeURIComponent(b.dataset.key),Number(b.dataset.qty));renderCart()});box.querySelectorAll('[data-remove-cart]').forEach(b=>b.onclick=()=>{removeCart(decodeURIComponent(b.dataset.removeCart));renderCart()});document.getElementById('clearV85').onclick=()=>{clearCart();renderCart()}}
 function boot(){links();enhanceHeader();sync();renderFavorites();renderCart();enhanceCards();enhanceProduct();setTimeout(()=>{enhanceHeader();enhanceCards();enhanceProduct();sync()},400)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
