/* MarquesMater V20 — chat profissional cliente */
(function(){
 if(window.__MM_CHAT_V10__)return;window.__MM_CHAT_V10__=true;
 const css=`#mm-chat{position:fixed;right:22px;bottom:22px;z-index:9999;font-family:Inter,Segoe UI,Arial,sans-serif}.mm-chat-bubble{position:relative;width:62px;height:62px;border:0;border-radius:50%;background:#f28a00;color:#fff;font-size:25px;box-shadow:0 12px 34px #1018203d;cursor:pointer;display:flex;align-items:center;justify-content:center}.mm-chat-box{display:none;width:390px;height:590px;background:#fff;border:1px solid #e0e5ea;border-radius:20px;box-shadow:0 24px 70px #1018203b;overflow:hidden;margin-bottom:12px}.mm-chat-box.open{display:flex;flex-direction:column}.mmc-head{background:#101820;color:#fff;padding:16px 18px;display:flex;justify-content:space-between;align-items:center}.mmc-head strong{display:block;font-size:16px}.mmc-head span{display:block;font-size:11px;opacity:.72;margin-top:3px}.mmc-close{border:0;background:transparent;color:#fff;font-size:24px}.mmc-pre{padding:18px;background:#fff;border-bottom:1px solid #e7ebef}.mmc-pre p{margin:0 0 12px;font-size:12px;color:#596670;line-height:1.5}.mmc-pre-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mmc-pre input{width:100%;border:1px solid #d5dce2;border-radius:9px;padding:10px;font-size:12px}.mmc-pre .full{grid-column:1/-1}.mmc-start{margin-top:2px;width:100%;border:0;background:#f28a00;color:#fff;border-radius:9px;padding:11px;font-weight:900}.mmc-body{flex:1;overflow:auto;padding:15px;background:#f5f7f9}.mmc-msg{max-width:82%;padding:10px 12px;border-radius:14px;margin:7px 0;font-size:13px;line-height:1.45;white-space:pre-wrap}.mmc-msg.me{margin-left:auto;background:#f28a00;color:#fff;border-bottom-right-radius:4px}.mmc-msg.them{background:#fff;border:1px solid #e0e5e9;border-bottom-left-radius:4px}.mmc-msg.system{background:transparent;border:0;text-align:center;color:#7a858e;max-width:100%;font-size:11px}.mmc-foot{display:flex;gap:7px;padding:10px;border-top:1px solid #e5e9ed;background:#fff}.mmc-foot input{flex:1;border:1px solid #d5dbe0;border-radius:9px;padding:10px;outline:none}.mmc-foot button{border:0;background:#101820;color:#fff;border-radius:9px;padding:0 14px;font-weight:900}.mmc-status{padding:7px 18px;background:#f7f8fa;border-bottom:1px solid #e7ebef;font-size:11px;color:#6c7780}.mmc-unread{position:absolute;right:-1px;top:-1px;background:#d62828;color:#fff;border-radius:99px;font-size:10px;padding:3px 6px;font-weight:900}@media(max-width:600px){#mm-chat{right:12px;bottom:12px}.mm-chat-box{width:calc(100vw - 24px);height:min(650px,82vh)}}`;
 const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
 const root=document.createElement('div');root.id='mm-chat';root.innerHTML=`<div class="mm-chat-box"><div class="mmc-head"><div><strong>💬 Fale connosco</strong><span>MarquesMater · apoio ao cliente</span></div><button class="mmc-close">×</button></div><div class="mmc-status">🟢 Atendimento online · resposta por ordem de chegada</div><div class="mmc-pre" id="mmc-pre"><p>Para começarmos, indique o seu nome. Email e telefone são opcionais.</p><div class="mmc-pre-grid"><input id="mmc-name" placeholder="Nome" required><input id="mmc-email" placeholder="Email"><input id="mmc-phone" class="full" placeholder="Telefone (opcional)"><button class="mmc-start full">Iniciar conversa</button></div></div><div class="mmc-body" id="mmc-msgs"></div><form class="mmc-foot" id="mmc-form"><input id="mmc-input" placeholder="Escreva a sua mensagem..." autocomplete="off"><button>Enviar</button></form></div><button class="mm-chat-bubble" aria-label="Abrir chat">💬<span class="mmc-unread" hidden>0</span></button>`;
 document.body.appendChild(root);
 const box=root.querySelector('.mm-chat-box'),bubble=root.querySelector('.mm-chat-bubble'),pre=root.querySelector('#mmc-pre'),msgs=root.querySelector('#mmc-msgs'),form=root.querySelector('#mmc-form'),input=root.querySelector('#mmc-input');let sid=localStorage.getItem('mm_chat_session')||'',started=false,lastCount=0;
 function add(text,who){const d=document.createElement('div');d.className='mmc-msg '+(who||'them');d.textContent=text;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight}
 function render(list){msgs.innerHTML='';list.forEach(m=>m.message&&add(m.message,m.sender==='customer'?'me':m.sender==='system'?'system':'them'));lastCount=list.length}
 async function init(){if(!sid)return;try{const r=await fetch('/api/chat/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sid,page:location.href,product:new URLSearchParams(location.search).get('slug')||''})});const j=await r.json();if(j.session_id){sid=j.session_id;started=true;localStorage.setItem('mm_chat_session',sid);pre.style.display='none';render(j.messages||[])}}catch{}}
 bubble.onclick=()=>{box.classList.toggle('open');if(box.classList.contains('open')){init();setTimeout(()=>input.focus(),80)}};root.querySelector('.mmc-close').onclick=()=>box.classList.remove('open');
 root.querySelector('.mmc-start').onclick=async()=>{const name=root.querySelector('#mmc-name').value.trim(),email=root.querySelector('#mmc-email').value.trim(),phone=root.querySelector('#mmc-phone').value.trim();if(!name){root.querySelector('#mmc-name').focus();return}try{const r=await fetch('/api/chat/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sid,name,email,phone,page:location.href,product:new URLSearchParams(location.search).get('slug')||''})});const j=await r.json();sid=j.session_id;localStorage.setItem('mm_chat_session',sid);started=true;pre.style.display='none';render(j.messages||[]);input.focus()}catch{alert('Não foi possível iniciar a conversa. Tente novamente.')}};
 form.onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;if(!started){root.querySelector('.mmc-start').click();return}input.value='';try{await fetch('/api/chat/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sid,message:text,page:location.href,product:new URLSearchParams(location.search).get('slug')||''})});await init()}catch{add('Não conseguimos enviar agora. Tente novamente.','them')}};
 setInterval(async()=>{if(!sid)return;try{const r=await fetch('/api/chat/messages?session_id='+encodeURIComponent(sid),{cache:'no-store'}),j=await r.json(),list=j.messages||[];if(list.length!==lastCount){const wasOpen=box.classList.contains('open');render(list);if(!wasOpen){const u=root.querySelector('.mmc-unread');u.hidden=false;u.textContent='Novo'}else{const u=root.querySelector('.mmc-unread');u.hidden=true}}}catch{}},2200);
 fetch('/api/site',{cache:'no-store'}).then(r=>r.json()).then(site=>{if(site.settings?.chat?.enabled===false)root.remove()}).catch(()=>{});
})();