from pathlib import Path
p=Path('server.py'); s=p.read_text(encoding='utf-8')

LOCAL_MARK='MM_NEUCE_LOCAL_IMAGES_RUNTIME_20260910'
local_code=r'''\n# MM_NEUCE_LOCAL_IMAGES_RUNTIME_20260910\ndef ensure_neuce_local_images_runtime():\n c=db(); local={\n  'neucegold-ng':'assets/products/6e80f7f25b22.png','superneuce':'assets/products/f75a704e3035.png','superneuce-sn':'assets/products/db85743313f0.png','belneuce':'assets/products/fe07c3d90546.png','aquaneuce':'assets/products/ff7c8f6fac86.jpg','primaneuce':'assets/products/a4d20107612f.png','multineuce':'assets/products/cd1ccfe26cad.jpg','hydroneuce':'assets/products/e63753742102.png','plioneuce':'assets/products/dda5d40c4e9b.png','textuneuce':'assets/products/3e8f17fb9750.jpg','neucetext':'assets/products/2321aa6501ee.png','woodneuce':'assets/products/9a1aabdd39bd.png','neucebel':'assets/neucebel-real.jpg','neucematt':'assets/neucematt-real.png','neucesoft':'assets/neucesoft-real.jpg'}\n for slug,img in local.items():\n  row=c.execute('SELECT slug FROM products WHERE slug=?',(slug,)).fetchone()\n  if row:c.execute('UPDATE products SET image=?,gallery_json=?,updated_at=CURRENT_TIMESTAMP WHERE slug=?',(img,json.dumps([img],ensure_ascii=False),slug))\n c.commit(); c.close()\nensure_neuce_local_images_runtime()\n'''

if 'MM_NEUCE_PAINTS_RUNTIME_20260910' not in s:
    code=r'''\n# MM_NEUCE_PAINTS_RUNTIME_20260910\ndef ensure_neuce_paints_runtime():\n c=db(); PR={'0.75L':'6,90 €','1L':'8,90 €','2.5L':'14,90 €','4L':'19,90 €','5L':'24,90 €','15L':'89,90 €'}\n products=[('neucegold-ng','NeuceGold NG','Tintas - Exteriores','https://www.neuce.com/p180-p-1128-neucegold-ng-pt_pt'),('superneuce','SuperNeuce','Tintas - Interiores','https://www.neuce.com/p179-cat-159-tinta-plastica-ni_pt'),('superneuce-sn','SuperNeuce SN','Tintas - Interiores','https://www.neuce.com/p180-p-1144-superneuce-sn-ni_pt'),('belneuce','BelNeuce','Tintas - Interiores','https://www.neuce.com/p179-cat-159-tinta-plastica-ni_pt'),('aquaneuce','AquaNeuce','Primários - Interiores','https://www.neuce.com/p180-p-885-aquaneuce-pt_pt'),('primaneuce','PrimaNeuce','Primários - Interiores','https://www.neuce.com/p180-p-1029-primaneuce-co_pt'),('multineuce','MultiNeuce','Primários - Interiores','https://www.neuce.com/p180-p-882-multineuce-mo_pt'),('hydroneuce','HydroNeuce','Primários - Exteriores','https://www.neuce.com/p180-p-884-hydroneuce-primario-pt_pt'),('plioneuce','PlioNeuce','Tintas - Exteriores','https://www.neuce.com/p179-cat-161-fachada-se_pt'),('textuneuce','TextuNeuce','Tintas - Exteriores','https://www.neuce.com/p180-p-894-textuneuce-pt_pt'),('neucetext','NeuceText','Tintas - Exteriores','https://www.neuce.com/p179-cat-160-tinta-texturada-pt_pt')]\n for slug,name,sub,url in products:\n  vars=[{'name':x,'price':PR[x],'stock':'Disponível'} for x in (['5L','15L'] if slug in ('neucegold-ng','plioneuce','textuneuce','neucetext','aquaneuce','primaneuce','multineuce','hydroneuce') else ['1L','5L','15L'])]\n  put_product(c,{'slug':slug,'name':name,'ref':'','family':'Pinturas','category':'Pinturas','subfamily':sub,'brand':'NEUCE','price_display':'Desde '+vars[0]['price'],'price':num(vars[0]['price']),'stock':0,'min_stock':5,'state':'active','description':'Produto NEUCE para pinturas, preparação e proteção de superfícies.','image':'assets/paint-placeholder.svg','gallery':['assets/paint-placeholder.svg'],'variants':vars,'docs':[{'title':'Produto no site oficial NEUCE','url':url}]})\n for slug,sub in {'neucebel':'Tintas - Interiores','neucematt':'Tintas - Interiores','neucesoft':'Tintas - Interiores'}.items(): c.execute("UPDATE products SET family='Pinturas',category='Pinturas',subfamily=?,brand='NEUCE' WHERE slug=?",(sub,slug))\n c.commit(); c.close()\nensure_neuce_paints_runtime()\n'''
    needle='\nseed_db()\nensure_rida_pricing()'
    if needle not in s: raise SystemExit('anchor not found')
    s=s.replace(needle,code.replace('\\n','\n')+needle,1)

if LOCAL_MARK not in s:
    anchor='ensure_neuce_paints_runtime()\n'
    if anchor not in s: raise SystemExit('runtime anchor not found')
    s=s.replace(anchor,anchor+local_code.replace('\\n','\n'),1)

p.write_text(s,encoding='utf-8')
